# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "354009510147a812607e4df29560460b"
application_url = "https://junk-genealogy-strongly-nothing.trycloudflare.com"
embedded = true
name = "salonist-remix"
handle = "salonist-remix-1"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products,write_inventory,write_locations,write_products,write_publications"

[auth]
redirect_urls = [
  "https://junk-genealogy-strongly-nothing.trycloudflare.com/auth/callback",
  "https://junk-genealogy-strongly-nothing.trycloudflare.com/auth/shopify/callback",
  "https://junk-genealogy-strongly-nothing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-840ac43c.myshopify.com"
automatically_update_urls_on_dev = true
