# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c38763fe7a276ba283c9eb1331506f1"
name = "salonist-remix"
handle = "salonist-remix"
application_url = "https://fiji-orange-filed-surrey.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products,write_inventory,write_locations,write_products,write_publications"

[auth]
redirect_urls = [
  "https://fiji-orange-filed-surrey.trycloudflare.com/auth/callback",
  "https://fiji-orange-filed-surrey.trycloudflare.com/auth/shopify/callback",
  "https://fiji-orange-filed-surrey.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
