# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c38763fe7a276ba283c9eb1331506f1"
name = "salonist-remix"
handle = "salonist-remix"
application_url = "https://verde-spot-balloon-discounts.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://verde-spot-balloon-discounts.trycloudflare.com/auth/callback",
  "https://verde-spot-balloon-discounts.trycloudflare.com/auth/shopify/callback",
  "https://verde-spot-balloon-discounts.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
